library(wesanderson)
library(fields)
library(viridisLite)
library(RColorBrewer)
library(magick)

library(INLA)
library(rgdal)
library(scales)
library(ggplot2)
library(sf) 
library(terra)
library(sp)
library(magick)
library(scales)
library(patchwork)

library(spatstat)

library(leaflet)
library(leafpop)
library(leaflet.extras)
library(htmltools)
library(tidyverse)
library(rnaturalearth)
library(lattice)
library(htmlwidgets)
library(widgetframe)
library(shiny)
library(mapdata)
library(maptools)
library(rgeos)
library(raster)
require(devtools)

library(ggmap)
library(stars)
library(fmesher)
library(viridis)

library(lbfgsb3c)
library(splines)